trigger:
  batch: true
  branches:
    include:
      - main
      - feature*

pool: 'hetzner'

variables:
  - group: AkkaSensors
  - name: IVY_HOME
    value: $(Pipeline.Workspace)/.ivy2

steps:

  - task: Bash@3
    displayName: 'Building and testing 2.13'
    inputs:
      targetType: 'inline'
      script: |
        sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} "++2.13.16; clean; coverage; test; coverageReport" && bash <(curl -s https://codecov.io/bash)
      failOnStderr: false
