trigger:
  batch: true
  branches:
    include:
      - main
      - feature*

pool: 'hetzner'

variables:
  - group: AkkaSensors
  - name: IVY_HOME
    value: $(Pipeline.Workspace)/.ivy2

steps:

  - task: Bash@3
    displayName: 'Building and testing'
    inputs:
      targetType: 'inline'
      script: |
        sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} "++2.13; test"
        sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} "++3.3; test"
      failOnStderr: false
