trigger:
  batch: true
  branches:
    include:
      - main
      - feature*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AkkaSensors
  - name: IVY_HOME
    value: $(Pipeline.Workspace)/.ivy2

steps:

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
      cleanDestinationDirectory: false

  - task: Bash@3
    displayName: 'Building and testing 2.13'
    inputs:
      targetType: 'inline'
      script: |
        sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} "++2.13; clean; coverage; test; coverageReport" && bash <(curl -s https://codecov.io/bash)
      failOnStderr: false

  - task: Bash@3
    displayName: 'Building and testing 3.3'
    inputs:
      targetType: 'inline'
      script: |
        sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} "++3.3; clean; test"
      failOnStderr: false
