trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AkkaSensors

steps:
  - task: DownloadSecureFile@1
    name: secring
    inputs:
      secureFile: secring.asc


  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
      cleanDestinationDirectory: false

  - task: Bash@3
    displayName: 'Build, sign and publish'
    inputs:
      targetType: 'inline'
      script: |
        echo $(tty)
        ls -la $(secring.secureFilePath)
        mkdir ~/.gnupg
        chmod -R 700 ~/.gnupg
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

        gpg --batch --import $(secring.secureFilePath)
        gpg --version
        gpg --list-keys
        gpg --list-secret-keys

        git checkout master
        git config --global user.email "tim@@pragmasoft.nl"
        git config --global user.name "Azure Devops release pipeline"

        sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} "++2.13.13; test"
        sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} "release with-defaults"

        rm -rf $(secring.secureFilePath)
        rm -rf ~/.gnupg

    env:
      RELEASE: true
      # passphrase will be passed to sbt plugin from here
      PGP_PASSPHRASE: $(gpg_pass)
      USERNAME: $(sonatype_user)
      PASSWORD: $(sonatype_password)
      # neeeded for gpg to work on headless azure agents
      GPG_TTY: /dev/pts/0
